// comparisons/bench/solid.bench.ts
// @ts-nocheck
// Solid.js — three chained createMemos for the top-K graph. Dashboard adds
// two parallel memos (liquidCount, avgBid) over the same per-row signals.

import { createSignal, createMemo, createRoot } from 'solid-js/dist/solid.js'
import { makeTrades, TICKS, THRESHOLD, TOP_K } from './workload.ts'
import { measure, pkgVersion, type BenchResult } from './measure.ts'

type Cell = {
  id: number
  bid: () => number
  setBid: (n: number) => void
  ask: () => number
  setAsk: (n: number) => void
}

function makeCells() {
  return makeTrades().map(t => {
    const [bid, setBid] = createSignal(t.bid)
    const [ask, setAsk] = createSignal(t.ask)
    return { id: t.id, bid, setBid, ask, setAsk }
  })
}

function buildSingle() {
  let cells: Cell[] = []
  let top = () => [] as any[]
  const dispose = createRoot(d => {
    cells = makeCells()
    const withSpread = createMemo(() => {
      const out = new Array(cells.length)
      for (let i = 0; i < cells.length; i++) {
        const c = cells[i]
        out[i] = { id: c.id, spread: c.ask() - c.bid() }
      }
      return out
    })
    const filtered = createMemo(() => withSpread().filter(t => t.spread > THRESHOLD))
    const memo = createMemo(() => [...filtered()].sort((a, b) => b.spread - a.spread).slice(0, TOP_K))
    top = memo
    void memo()
    return d
  })
  return { cells, top, dispose }
}

function buildDashboard() {
  let cells: Cell[] = []
  let liquidCount = () => 0
  let top10 = () => [] as any[]
  let avgBid = () => 0
  const dispose = createRoot(d => {
    cells = makeCells()
    liquidCount = createMemo(() => {
      let n = 0
      for (let i = 0; i < cells.length; i++) {
        const c = cells[i]
        if (c.ask() - c.bid() > THRESHOLD) n++
      }
      return n
    })
    const withSpread = createMemo(() => {
      const out = new Array(cells.length)
      for (let i = 0; i < cells.length; i++) {
        const c = cells[i]
        out[i] = { id: c.id, spread: c.ask() - c.bid() }
      }
      return out
    })
    const filtered = createMemo(() => withSpread().filter(t => t.spread > THRESHOLD))
    top10 = createMemo(() => [...filtered()].sort((a, b) => b.spread - a.spread).slice(0, TOP_K))
    avgBid = createMemo(() => {
      let s = 0
      for (let i = 0; i < cells.length; i++) s += cells[i].bid()
      return s / cells.length
    })
    void liquidCount(); void top10(); void avgBid()
    return d
  })
  return { cells, liquidCount, top10, avgBid, dispose }
}

function tick(cells, t) {
  if (t.field === 'bid') cells[t.idx].setBid(t.newValue)
  else cells[t.idx].setAsk(t.newValue)
}

export default function bench(): BenchResult {
  const setup = measure(() => {
    const g = buildSingle()
    g.dispose()
  })

  const single = (() => {
    const { cells, top } = buildSingle()
    let i = 0
    return measure(() => {
      tick(cells, TICKS[i++ % TICKS.length])
      void top()
    })
  })()

  const stream = (() => {
    const { cells, top } = buildSingle()
    return measure(() => {
      for (let j = 0; j < TICKS.length; j++) {
        tick(cells, TICKS[j])
        void top()
      }
    })
  })()

  const dashboard = (() => {
    const { cells, liquidCount, top10, avgBid } = buildDashboard()
    return measure(() => {
      for (let j = 0; j < TICKS.length; j++) {
        tick(cells, TICKS[j])
        void liquidCount()
        void top10()
        void avgBid()
      }
    })
  })()

  return {
    name: 'solid',
    version: pkgVersion('solid-js'),
    setup,
    single,
    batch: stream,
    dashboard,
    notes: 'per-row signals + chained memos; dashboard = 3 parallel memos',
  }
}

// comparisons/bench/react.bench.ts
// @ts-nocheck
// react + react-test-renderer — useState(trades) + chained useMemo, then a
// dashboard with three parallel useMemos. Idiomatic React reactivity: setState
// replaces the array reference; useMemo skips work when deps are
// reference-equal, recomputes when they change.
//
// We use react-test-renderer (no DOM) so the same runtime that runs in
// production handles state + memo dependency tracking. Each tick goes through
// `act()` so the render flushes synchronously and the new memo result is
// readable inside the timed region.
//
// React 19 marks react-test-renderer deprecated; the runtime is still correct.

import './react-act-env.ts'
import React, { useState, useMemo } from 'react'
import TestRenderer from 'react-test-renderer'
import { makeTrades, TICKS, THRESHOLD, TOP_K } from './workload.ts'
import { measure, pkgVersion, type BenchResult } from './measure.ts'

const { act, create } = TestRenderer
const h = React.createElement

function makeSingle() {
  let setTradesRef: (fn: any) => void
  let topRef: any
  function App() {
    const [trades, setTrades] = useState(makeTrades)
    const withSpread = useMemo(
      () => trades.map(t => ({ id: t.id, spread: t.ask - t.bid })),
      [trades],
    )
    const filtered = useMemo(
      () => withSpread.filter(t => t.spread > THRESHOLD),
      [withSpread],
    )
    const top = useMemo(
      () => [...filtered].sort((a, b) => b.spread - a.spread).slice(0, TOP_K),
      [filtered],
    )
    setTradesRef = setTrades
    topRef = top
    return null
  }
  return {
    App,
    setTrades: (fn: any) => setTradesRef(fn),
    getTop: () => topRef,
  }
}

function makeDashboard() {
  let setTradesRef: (fn: any) => void
  const out: any = {}
  function App() {
    const [trades, setTrades] = useState(makeTrades)
    const liquidCount = useMemo(() => {
      let n = 0
      for (let i = 0; i < trades.length; i++) {
        const t = trades[i]
        if (t.ask - t.bid > THRESHOLD) n++
      }
      return n
    }, [trades])
    const withSpread = useMemo(
      () => trades.map(t => ({ id: t.id, spread: t.ask - t.bid })),
      [trades],
    )
    const filtered = useMemo(
      () => withSpread.filter(t => t.spread > THRESHOLD),
      [withSpread],
    )
    const top10 = useMemo(
      () => [...filtered].sort((a, b) => b.spread - a.spread).slice(0, TOP_K),
      [filtered],
    )
    const avgBid = useMemo(() => {
      let s = 0
      for (let i = 0; i < trades.length; i++) s += trades[i].bid
      return s / trades.length
    }, [trades])
    setTradesRef = setTrades
    out.liquidCount = liquidCount
    out.top10 = top10
    out.avgBid = avgBid
    return null
  }
  return {
    App,
    setTrades: (fn: any) => setTradesRef(fn),
    read: out,
  }
}

function buildSingle() {
  const m = makeSingle()
  let renderer: any
  act(() => { renderer = create(h(m.App)) })
  return { ...m, renderer }
}

function buildDashboard() {
  const m = makeDashboard()
  let renderer: any
  act(() => { renderer = create(h(m.App)) })
  return { ...m, renderer }
}

function tick(setTrades, t) {
  act(() => {
    setTrades((prev: any[]) => {
      const next = prev.slice()
      next[t.idx] = { ...next[t.idx], [t.field]: t.newValue }
      return next
    })
  })
}

export default function bench(): BenchResult {
  const setup = measure(() => {
    const g = buildSingle()
    act(() => { g.renderer.unmount() })
  })

  const single = (() => {
    const { setTrades, getTop } = buildSingle()
    let i = 0
    return measure(() => {
      tick(setTrades, TICKS[i++ % TICKS.length])
      void getTop()
    })
  })()

  const stream = (() => {
    const { setTrades, getTop } = buildSingle()
    return measure(() => {
      for (let j = 0; j < TICKS.length; j++) {
        tick(setTrades, TICKS[j])
        void getTop()
      }
    })
  })()

  const dashboard = (() => {
    const { setTrades, read } = buildDashboard()
    return measure(() => {
      for (let j = 0; j < TICKS.length; j++) {
        tick(setTrades, TICKS[j])
        void read.liquidCount
        void read.top10
        void read.avgBid
      }
    })
  })()

  return {
    name: 'react',
    version: pkgVersion('react'),
    setup,
    single,
    batch: stream,
    dashboard,
    notes: 'useState + useMemo chain; setState replaces array reference, full chain re-runs each tick',
  }
}
